version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: naukriwaala
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/naukriwaala
      - API_KEY=${API_KEY:-default_dev_key}
    depends_on:
      db:
        condition: service_healthy

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/naukriwaala
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: 