services:
  scraper:
    build:
      context: ./backend
      dockerfile: Dockerfile.scraper
    command: >
      poetry run python -m src.scrapers.opportunities_scraper
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    ports:
      - "8001:8001"
    networks:
      - naukriwaala-default

networks:
  naukriwaala-default:
    external: true
