# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Chaturai
site_description: "ChaturAI Documentation"
site_url: https://docs.chaturai.com/
repo_url: https://github.com/IDinsight/chaturai
copyright: "© 2025 IDinsight"
extra:
  analytics:
    provider: google
    property: G-K07FFTMFTN
  generator: false
  social:
    - icon: material/shield-lock
      link: https://www.idinsight.org/about/privacy-policy/
      name: Privacy Policy
  version:
    provider: mike
    alias: true
    default: latest

nav:
  - Home:
      - "": index.md
      - Usage: usage.md
      - Roadmap: roadmap.md

  - Latest Updates:
      - blog/index.md

  - Components:
      - Overview: components/index.md
      - Apprenticeship Recommendation:
          - Overview: components/apprenticeship-recommendation/index.md
      - Automated Registration:
          - Overview: components/automated-registration/index.md
      - Career Coaching:
          - Overview: components/career-coaching/index.md

  - Integrations:
      - integrations/index.md
      - Chat Managers:
          - Turn.io: integrations/chat_managers/turn.io/turn.md

  - Deployment:
      - Quick Setup with Docker Compose: deployment/quick-setup.md

  - Contribute:
      - Guidelines: development/contributing.md
      - Setup: develop/local_setup.md

  - Contact us:
      - Team: contact_us.md

# Themes and extensions
theme:
  name: material
  logo: images/logo-light.png
  favicon: images/favicon.png
  font:
    text: "Inter"
    code: "Roboto Mono"
  palette:
    - scheme: slate # Palette toggle for dark mode
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default # Palette toggle for light mode
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - content.code.copy
    - navigation.sections
    - navigation.indexes
    - navigation.top

  icon:
    admonition:
      note: material/alert-circle
    annotation: material/help-circle

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      title: On this page
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - glightbox
  - search
  - blog:
      post_excerpt: required
  - open-in-new-tab
