# PATH variables must be set in .env files.
services:
  caddy:
    image: caddy:2.7.6
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${PATHS_PROJECT_DIR}/cicd/deployment/docker-compose/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - ${PATHS_PROJECT_DIR}/.env
    depends_on:
      - api

  api:
    build:
      context: ${PATHS_PROJECT_DIR}/backend
      dockerfile: ./Dockerfile.api
    command: >
      /bin/sh -c "
      python -m alembic upgrade head &&
      python src/chaturai/entries/main.py"
    expose:
      - "8000"
    environment:
      - POSTGRES_HOST=db
      - LITELLM_ENDPOINT=http://litellm-proxy:4000
      - REDIS_HOST=redis://redis
      - PATHS_PROJECT_DIR=/usr/src/chaturai
      - PATHS_LOGS_DIR=/usr/src/chaturai/logs
      - PATHS_SECRETS_DIR=/usr/src/chaturai/secrets
    env_file:
      - ${PATHS_PROJECT_DIR}/.env
      - ${PATHS_PROJECT_DIR}/backend/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    env_file:
      - ${PATHS_PROJECT_DIR}/backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  litellm-proxy:
    command: ["--config", "/app/config.yaml", "--detailed_debug", "--telemetry", "False"]
    container_name: litellm-proxy
    env_file:
      - ${PATHS_PROJECT_DIR}/cicd/litellm/.env
    image: ghcr.io/berriai/litellm:main-v1.67.0-stable
    ports:
      - "4000:4000"
      - "4001:4001"  # Debugging port for LiteLLM
    restart: always
    volumes:
      - ${PATHS_SECRETS_DIR}/gcp_credentials.json:/app/gcp_credentials.json
      - ${PATHS_PROJECT_DIR}/cicd/litellm/litellm_config.yaml:/app/config.yaml

  redis:
    container_name: redis-local
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
      - "6380:6380"  # Debugging port for Redis
    restart: always

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  redis_data:
