# PATH variables must be set in .env files.
services:
  caddy:
    logging:
      driver: awslogs
      options:
        awslogs-region: "ap-south-1"
        awslogs-group: "chaturai-testing"
        awslogs-stream: caddy-container
        awslogs-create-group: "true"

  api:
    environment:
      - CHAT_ENV=testing
      - LOGFIRE_ENVIRONMENT=testing

    logging:
      driver: awslogs
      options:
        awslogs-region: "ap-south-1"
        awslogs-group: "chaturai-testing"
        awslogs-stream: api-container
        awslogs-create-group: "true"

  db:
    logging:
      driver: awslogs
      options:
        awslogs-region: "ap-south-1"
        awslogs-group: "chaturai-testing"
        awslogs-stream: db-container
        awslogs-create-group: "true"

  redis:
    logging:
      driver: awslogs
      options:
        awslogs-region: "ap-south-1"
        awslogs-group: "chaturai-testing"
        awslogs-stream: redis-container
        awslogs-create-group: "true"

  litellm-proxy:
    logging:
      driver: awslogs
      options:
        awslogs-region: "ap-south-1"
        awslogs-group: "chaturai-testing"
        awslogs-stream: litellm-proxy-container
        awslogs-create-group: "true"
