# PATH variables must be set in .env files.
services:
  scraper:
    build:
      context: ${PATHS_PROJECT_DIR}//backend
      dockerfile: Dockerfile.scraper
    command: >
      poetry run python -m src.scrapers.opportunities_scraper
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    ports:
      - "8001:8001"
    networks:
      - chaturai-dev_default

networks:
  chaturai-dev_default:
    external: true
