authors:
  Jahnavi Meher:
    name: Jahnavi Meher
    description: Senior Product Manager
    avatar: https://raw.githubusercontent.com/IDinsight/chaturai/main/docs/images/author-avatars/jahnavi.png
  Suzin You:
    name: Suzin You
    description: Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/chaturai/main/docs/images/author-avatars/suzin.png
  Tony Zhao:
    name: Tony Zhao
    description: Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/chaturai/main/docs/images/author-avatars/tony.png
