authors:
  Jahnavi:
    name: Jahnavi
    description: Senior Product Manager
    avatar: https://raw.githubusercontent.com/IDinsight/chaturai/main/docs/images/author-avatars/jahnavi.png
  Suzin:
    name: Suzin
    description: Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/chaturai/main/docs/images/author-avatars/suzin.png
  Tony:
    name: Tony
    description: Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/chaturai/main/docs/images/author-avatars/tony.png
