name: Deploy Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies (docs group only)
        run: |
          cd backend
          poetry install --only docs

      - name: Build and push docs version
        run: |
          cd backend
          poetry run mkdocs gh-deploy --config-file ../mkdocs.yml --force

      # - name: Add CNAME
      #   run: |
      #     git switch gh-pages
      #     echo "docs.chaturai.com" >> CNAME
      #     git add CNAME
      #     git commit -m "Add CNAME"
      #     git push -f origin gh-pages
